# Generated by Django 5.1.7 on 2025-11-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("age", models.IntegerField()),
                ("place", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=9, max_digits=11, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=9, max_digits=11, null=True
                    ),
                ),
                ("role", models.CharField(default="user", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="tbl_doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("qualification", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("phno", models.CharField(max_length=15)),
                ("doctor_image", models.ImageField(upload_to="doctor_images/")),
                ("id_proof", models.ImageField(upload_to="id_proofs/")),
                ("expirience", models.CharField(max_length=100)),
                ("hospital_name", models.CharField(max_length=255)),
                ("hospital_address", models.TextField()),
                ("hospital_phno", models.CharField(max_length=20)),
                (
                    "hospital_place",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=9, max_digits=11, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=9, max_digits=11, null=True
                    ),
                ),
                ("doctor_id", models.CharField(max_length=100)),
                ("role", models.CharField(default="doctor", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
