# Generated by Django 5.2.8 on 2025-11-29 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("femitimeapp", "0003_tbl_hospital_doctor_register_delete_tbl_doctor"),
    ]

    operations = [
        migrations.CreateModel(
            name="HospitalDoctorTimeSlotGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("timeslots", models.JSONField(blank=True, default=list)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slot_groups",
                        to="femitimeapp.tbl_hospital_doctor_register",
                    ),
                ),
            ],
        ),
    ]
