# Generated by Django 5.2.8 on 2025-11-29 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("femitimeapp", "0004_hospitaldoctortimeslotgroup"),
    ]

    operations = [
        migrations.CreateModel(
            name="HospitalBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.CharField(max_length=20)),
                ("status", models.CharField(default="booked", max_length=20)),
                ("is_booked", models.BooleanField(default=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="femitimeapp.tbl_hospital_doctor_register",
                    ),
                ),
                (
                    "timeslot_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="femitimeapp.hospitaldoctortimeslotgroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="femitimeapp.register",
                    ),
                ),
            ],
        ),
    ]
