# Generated by Django 5.2.8 on 2025-12-01 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("femitimeapp", "0005_hospitalbooking"),
    ]

    operations = [
        migrations.CreateModel(
            name="CycleInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_day_of_period", models.DateField()),
                (
                    "duration",
                    models.IntegerField(help_text="Duration of period in days"),
                ),
                ("flow_intensity", models.TextField(blank=True, null=True)),
                (
                    "symptoms",
                    models.TextField(
                        blank=True,
                        help_text="List symptoms like cramps, headache, etc.",
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "average_cycle_length",
                    models.IntegerField(
                        blank=True, help_text="Average cycle length in days", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cycle_inputs",
                        to="femitimeapp.register",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HospitalDoctorFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField()),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospital_feedbacks",
                        to="femitimeapp.tbl_hospital_doctor_register",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospital_feedbacks",
                        to="femitimeapp.register",
                    ),
                ),
            ],
        ),
    ]
