# Generated by Django 5.2.8 on 2025-12-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("femitimeapp", "0006_cycleinput_hospitaldoctorfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictionresult",
            name="acne",
            field=models.CharField(default="0", max_length=50),
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="age",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="blood_group",
            field=models.CharField(default="Unknown", max_length=10),
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="bmi",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="cycle_regularity",
            field=models.CharField(default="0", max_length=50),
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="fast_food_consumption",
            field=models.CharField(default="0", max_length=50),
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="hair_growth",
            field=models.CharField(default="0", max_length=50),
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="height",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="mood_swings",
            field=models.CharField(default="0", max_length=50),
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="pulse_rate",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="skin_darkening",
            field=models.CharField(default="0", max_length=50),
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="weight",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="predictionresult",
            name="result",
            field=models.CharField(default="Pending", max_length=50),
        ),
    ]
