# Generated by Django 5.2.8 on 2025-12-01 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("femitimeapp", "0007_predictionresult_acne_predictionresult_age_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TblPredictionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField(default=0)),
                ("weight", models.FloatField(default=0)),
                ("height", models.FloatField(default=0)),
                ("bmi", models.FloatField(default=0)),
                ("fast_food_consumption", models.CharField(default="0", max_length=50)),
                ("blood_group", models.CharField(default="Unknown", max_length=10)),
                ("pulse_rate", models.FloatField(default=0)),
                ("cycle_regularity", models.CharField(default="0", max_length=50)),
                ("hair_growth", models.CharField(default="0", max_length=50)),
                ("acne", models.CharField(default="0", max_length=50)),
                ("mood_swings", models.CharField(default="0", max_length=50)),
                ("skin_darkening", models.CharField(default="0", max_length=50)),
                ("pdf_file", models.FileField(upload_to="medical_reports/")),
                ("result", models.CharField(default="Pending", max_length=50)),
                ("extracted_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="femitimeapp.register",
                    ),
                ),
            ],
        ),
    ]
