# Generated by Django 5.2.8 on 2026-01-16 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("femitimeapp", "0008_tblpredictionresult"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tblpredictionresult",
            name="pulse_rate",
        ),
    ]
