# Generated by Django 5.2.8 on 2026-01-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("femitimeapp", "0009_remove_tblpredictionresult_pulse_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="tblpredictionresult",
            name="pulse_rate",
            field=models.FloatField(default=0),
        ),
    ]
