# Generated by Django 5.2.8 on 2026-01-24 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("femitimeapp", "0010_tblpredictionresult_pulse_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tblpredictionresult",
            name="pulse_rate",
        ),
    ]
