# Generated by Django 5.2.8 on 2026-01-28 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("femitimeapp", "0013_remove_tblpredictionresult_pulse_rate"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PredictionResult",
        ),
    ]
