# Generated by Django 5.2.8 on 2026-02-17 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('femitimeapp', '0014_delete_predictionresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldoctorfeedback',
            name='booking',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='femitimeapp.hospitalbooking'),
            preserve_default=False,
        ),
    ]
